### ISSUE TITLE
not working when building for production

### ISSUE THREAD

**Issue by fjrial** [ronglasmann/node-sql-db#1]
Hi:

I started to use your module some days ago, because it provides basically what I want: sqlite or mysql access.

My database file resides in my "userData" folder (building with electron-builder)

Everything is working fine in development mode, it can open, connect and use the database
But when building for production (the database file is the same).. it can't establish the db connection.

This code is that I'm using to connect to the database in dev and also production releases.

`var db = new SQL.Db({
            platform: "SQLite",
            file: filedb ,
            schema: []
        });`

filedb is a var containing a string pointing to the db location.. in my case is "/home/jrial/.config/folder/file.sqlite", as I said, the same for dev and production environments

Error in devTools:

> Uncaught Error: SQLITE_IOERR: disk I/O error
    at Function.module.exports.loopWhile (/tmp/.mount_affiniSV1UuE/app/resources/app.asar/node_modules/deasync/index.js:72:22)
    at new Db (/tmp/.mount_affiniSV1UuE/app/resources/app.asar/node_modules/node-sql-db/sql-db.js:81:21)

Any help will be apreciated

**Comment by fjrial** [comment]
Forget it, just my fault, while trying to use a db already in use.
